package texnologia.logismikou;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import texnologia.logismikou.FoodDeliverySystem1;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import java.lang.reflect.Method; 
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import java.sql.Statement;  
import javax.swing.JButton;
import java.lang.String;
import javax.swing.JCheckBox;
import javax.swing.JPanel;


/**
 *
 * @author Lyprandos
 */
public class StoresMenu extends javax.swing.JFrame  {
 static Connection conn;
 private JCheckBox cashCheckBox;
private JCheckBox cardCheckBox;

    
    public StoresMenu() {
        initComponents();
        connectiontoDB();
        getStoreNames();
        insertIntoDB();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
          cashCheckBox = new JCheckBox("Cash");
        cardCheckBox = new JCheckBox("Card");
        jFrame1 = new javax.swing.JFrame();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>(listModel);
        jButton4 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Store");

        jButton1.setText("Show Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Store's Menu");

        jButton2.setText("Add To Cart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Cart");

        jButton3.setText("Complete Order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList1);

        jButton4.setText("Remove");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

    JPanel paymentPanel = new JPanel();
    paymentPanel.add(cashCheckBox);
    paymentPanel.add(cardCheckBox);
    
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(212, 212, 212)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(41, 41, 41)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton4)
                    .addGap(213, 213, 213)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(paymentPanel))
            .addGap(612, 612, 612))
                )
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(83, 83, 83)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(57, 57, 57)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(65, 65, 65))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jButton4)
                    .addGap(44, 44, 44)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(paymentPanel)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
            .addGap(32, 32, 32))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
            
         
    
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
            jButton1.addActionListener(new ActionListener(){
                        public void actionPerformed(ActionEvent e){
                              String name = jComboBox1.getSelectedItem().toString(); 
                             
                               
                                if (name.equals("CafeGiwGiw")){
                                    jComboBox2.removeAllItems();
//                                        listModel.clear();
//                                        JFrame popupFrame = new JFrame("Cafe Giw Giw Menu");
//                                        popupFrame.setSize(400, 200);
//                                        
//                                        
//                                        
//                                        loadDataFromDatabase(listModel, "Select * from cafegiwgiw");
//                                         popupFrame.add(new JScrollPane(list));
//                                         popupFrame.setVisible(true);
                                           loadMenuForStore("Select * from cafegiwgiw");
                                        
                                       
                                }
                                else if (name.equals("Pizza-Varv")){
                                    jComboBox2.removeAllItems();
//                                    listModel.clear();
//                                       JFrame popupFrame = new JFrame("Pizza Varv");
//                                        popupFrame.setSize(400, 200);
//                                        
//                                        
//                                        loadDataFromDatabase(listModel, "Select * from pizza_varv");
//                                         popupFrame.add(new JScrollPane(list));
//                                         popupFrame.setVisible(true);
                                    loadMenuForStore("Select * from pizza_varv");
                                        
                                }
                                else if (name.equals("Souvlakopoly")){
                                        jComboBox2.removeAllItems();
//                                        listModel.clear();
//                                        JFrame popupFrame = new JFrame("SouvlakopoLy");
//                                        popupFrame.setSize(400, 200);
//                                        
//                                        
//                                        loadDataFromDatabase(listModel, "Select * from souvlakopoly");
//                                         popupFrame.add(new JScrollPane(list));
//                                         popupFrame.setVisible(true);
                                           loadMenuForStore("Select * from souvlakopoly");
                                         
                                }
                              
                        }
                        
            });
            
            
        
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            String item = jComboBox2.getSelectedItem().toString();
            listModel.addElement(item);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                // TODO add your handling code here:
                listModel.removeElementAt(jList1.getSelectedIndex());
    }//GEN-LAST:event_jButton4ActionPerformed

   private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    if (jList1.getModel().getSize() > 0) {
        String paymentMethod = "";
        if (cashCheckBox.isSelected()) {
            paymentMethod = "Cash";
        } else if (cardCheckBox.isSelected()) {
            paymentMethod = "Card";
        }
        
        if (paymentMethod.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a payment method.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        insertIntoDB(); // Make sure to include the payment method in the database insertion
        JOptionPane.showMessageDialog(this, "Order completed successfully with " + paymentMethod + ". It is going to arrive soon.", "Success", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Cart is empty. Add items to your cart before completing the order.", "Warning", JOptionPane.WARNING_MESSAGE);
    }
}//GEN-LAST:event_jButton3ActionPerformed
//GEN-LAST:event_jButton3ActionPerformed
                    
           
    /**
     * @param args the command line arguments
     */
        // συνδεση με το db
    public void connectiontoDB() {
        try {
           
            Class.forName("com.mysql.cj.jdbc.Driver");

           
            this.conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/texnologia", "root", "");
            System.out.println("Connection established successfully.");

          

        } catch (Exception e) {
            e.printStackTrace();

           
            if (this.conn == null) {
                System.out.println("No connection to the database.");
            }
        }
    }
    
   
    // 
    public void loadMenuForStore(String q){
        Statement st = null;
        ResultSet rs = null;
        
        try {
           
            
             
            st = conn.prepareStatement(q);

           
            rs = st.executeQuery(q);

            
            while (rs.next()) {
                String itemName = rs.getString("Product");  
                jComboBox2.addItem(itemName);
                
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error fetching data from the database: " + ex.getMessage(),
                                          "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    // διαβαζει απο την βαση τα μαγαζια
     public List<String> getStoreNames() {
        List<String> storeNames = new ArrayList<>();
        String query = "SELECT * FROM stores";
         

      
        if (this.conn == null) { 
            System.out.println("Cannot retrieve store names because the connection to the database was not established.");
            return storeNames;
        }

        try (Statement st = this.conn.createStatement(); 
             ResultSet rs = st.executeQuery(query)) {


            while (rs.next()) {
                int storeId = rs.getInt("store_id");
                String storeName = rs.getString("store_name");
            

                jComboBox1.addItem(storeName);
               

            }
            
           
              
            

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return storeNames;
    }
        // ανακτα πληροφοριες απο καθε μαγαζι ξεχωριστα
     // δεχεται ως παραμετρο το μαγαζι σαν string για να το χρησιμοποιησει ως query
      public static void loadDataFromDatabase(DefaultListModel<String> listModel, String Query) {

          
       
        Statement st = null;
        ResultSet rs = null;
        
        try {
           
            
             
            st = conn.prepareStatement(Query);

           
            rs = st.executeQuery(Query);

            
            while (rs.next()) {
                String itemName = rs.getString("Product");  
                
                
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error fetching data from the database: " + ex.getMessage(),
                                          "Database Error", JOptionPane.ERROR_MESSAGE);
        }
        
        }
     // καταγραφει τις παραγγελιες
      public  void insertIntoDB(){
            String sql = "Insert into Orders(Items) values (?)";
                       try {
        
          java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
         
        for (int i = 0; i < jList1.getModel().getSize(); i++) {
            String item = jList1.getModel().getElementAt(i);

           
            pstmt.setString(1, item);

            
            pstmt.executeUpdate();
            
        }

        System.out.println("Items inserted successfully.");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error inserting data into the database: " + e.getMessage(),
                                      "Database Error", JOptionPane.ERROR_MESSAGE);
    }
      }
      
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoresMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoresMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoresMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoresMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
      
          
        
          
         
               //ανοιγει το παραθυρο
               new StoresMenu().setVisible(true);
               
               
              
            }
        });
       
    }
        
    

         
         
    DefaultListModel<String> listModel = new DefaultListModel<>();
   

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
     
}

